### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Daviid-P** [moonlight-stream/moonlight-android#1137]
```log
10-08 15:11:58.786  8706  6928 E AndroidRuntime: FATAL EXCEPTION: Thread-881
10-08 15:11:58.786  8706  6928 E AndroidRuntime: Process: com.limelight.root, PID: 8706
10-08 15:11:58.786  8706  6928 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'org.jcodec.codecs.h264.io.model.VUIParameters$BitstreamRestriction org.jcodec.codecs.h264.io.model.VUIParameters.bitstreamRestriction' on a null object reference
10-08 15:11:58.786  8706  6928 E AndroidRuntime: 	at com.limelight.binding.video.MediaCodecDecoderRenderer.submitDecodeUnit(MediaCodecDecoderRenderer.java:770)
10-08 15:11:58.786  8706  6928 E AndroidRuntime: 	at com.limelight.nvstream.jni.MoonBridge.bridgeDrSubmitDecodeUnit(MoonBridge.java:160)
10-08 15:11:58.793   815   881 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - Task=3920#0
10-08 15:11:58.764  1671 10074 D ActivityManager: Raise procstate to external provider: ProcessRecord{eff2ae1 4783:com.google.android.gms/u999a30}
10-08 15:11:58.796  1671 10074 W ActivityManager:   Force finishing activity com.limelight.root/com.limelight.Game
10-08 15:11:58.797  1671 10074 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
10-08 15:11:58.806  1671  1684 D ActivityManager: Raise procstate to external provider: ProcessRecord{eff2ae1 4783:com.google.android.gms/u999a30}
10-08 15:11:58.808  1671  1684 I Timeline: Timeline: App_transition_ready time:41192206
```

I've tried playing with the H.265 setting  but nothing, sometimes it works and I can play, sometimes it crashes. No idea what makes a difference.

**Comment by Daviid-P** [comment]
Using 517.48 drivers I'm going to downgrade to 516.59 which is what I had before and see if it starts working again.

**Comment by Daviid-P** [comment]
I was running a Moonlight version 9.8.7
