### ISSUE TITLE
[Issue]: Handshake failed during pairing on android 5.1.1

### ISSUE THREAD

**Issue by nebulakl** [moonlight-stream/moonlight-android#1228]
### Describe the bug

I'm not able to pair my PC running Sunshine on an old android 5.1.1 device as I'm getting a Handshake failed error.
pairing the same PC using a newer android 11 device works.
both android devices have Moonlight Android v11.0 non root installed. 

### Steps to reproduce

1. open moonlight on an android 5.1.1 device and attempt to pair to a sunshine server
2. enter PIN in sunshine
3. moonlight prompts Handshake failed

### Affected games

not applicable

### Other Moonlight clients

PC

### Moonlight adjusted settings

No

### Moonlight adjusted settings (please complete the following information)

not applicable

### Moonlight default settings

Yes

### Gamepad-related connection issue

No

### Gamepad-related input issue

No

### Gamepad-related streaming issue

No

### Android version

5.1.1

### Device model

samsung SM-P601

### Server PC OS version

windows 11 22h2

### Server PC GeForce Experience version

sunshine 0.20.0

### Server PC Nvidia GPU driver version

535.98

### Server PC antivirus and firewall software

windows defender and windows firewall

### Relevant log output

```Shell
W/System.err(17057): javax.net.ssl.SSLHandshakeException: Handshake failed
W/System.err(17057):    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:435)
W/System.err(17057):    at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:320)
W/System.err(17057):    at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
W/System.err(17057):    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
W/System.err(17057):    at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:258)
W/System.err(17057):    at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
W/System.err(17057):    at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
W/System.err(17057):    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
W/System.err(17057):    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(17057):    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(17057):    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
W/System.err(17057):    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(17057):    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(17057):    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
W/System.err(17057):    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(17057):    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
W/System.err(17057):    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
W/System.err(17057):    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
W/System.err(17057):    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
W/System.err(17057):    at okhttp3.RealCall.execute(RealCall.java:93)
W/System.err(17057):    at com.limelight.nvstream.http.NvHTTP.openHttpConnection(NvHTTP.java:440)
W/System.err(17057):    at com.limelight.nvstream.http.NvHTTP.openHttpConnectionToString(NvHTTP.java:467)
W/System.err(17057):    at com.limelight.nvstream.http.NvHTTP.executePairingChallenge(NvHTTP.java:709)
W/System.err(17057):    at com.limelight.nvstream.http.PairingManager.pair(PairingManager.java:278)
W/System.err(17057):    at com.limelight.PcView$7.run(PcView.java:429)
W/System.err(17057):    at java.lang.Thread.run(Thread.java:818)
W/System.err(17057): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0xae850200: Failure in SSL library, usually a protocol error
W/System.err(17057): error:14094410:SSL routines:SSL3_READ_BYTES:sslv3 alert handshake failure (external/openssl/ssl/s3_pkt.c:1304 0xae890700:0x00000003)
W/System.err(17057):    at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
W/System.err(17057):    at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:347)
W/System.err(17057):    ... 25 more
```

**Comment by nlevi-dev** [comment]
I posted a fix for this [here](https://github.com/moonlight-stream/moonlight-android/issues/1300#issuecomment-3813171381).
