### ISSUE TITLE
PC streaming

### ISSUE THREAD

**Issue by Juzziee** [moonlight-stream/moonlight-android#125]
Hey guys, 

Having an issue with the Windows/Linux software.

I am not sure how to actually start the a game stream using these. I have downloaded the correct jar file and executing that through cmd or terminal. 

"java -jar moonlight.jar -host x.x.x.x -fs -720 -30fps"

When I do this, I am prompted that I am

"Using a deprecated app lookup method - Please specify an app ID in your StreamConfiguration instead"

I have tried add -app 202 (202 is Half Life 2s steam ID) but the same issue. Any advice?

**Comment by Juzziee** [comment]
C:\Users\Juzzy\Downloads>java -jar moonlight-win32.jar -host 127.0.0.1
Dec 19, 2015 3:11:06 AM com.limelight.LimeLog info
INFO: Reading Preferences
Dec 19, 2015 3:11:06 AM com.limelight.LimeLog info
INFO: 0 has attached.
Dec 19, 2015 3:11:06 AM com.limelight.LimeLog info
INFO: Writing Preferences
Dec 19, 2015 3:11:07 AM com.limelight.LimeLog info
INFO: Starting Steam
Dec 19, 2015 3:11:07 AM com.limelight.LimeLog info
INFO: Loaded key pair from disk
Dec 19, 2015 3:11:07 AM com.limelight.LimeLog info
INFO: Server major version: 4
Dec 19, 2015 3:11:07 AM com.limelight.LimeLog info
INFO: Using deprecated app lookup method - Please specify an app ID in your StreamConfiguration instead
java.net.SocketTimeoutException: timeout
        at okio.Okio$3.newTimeoutException(Okio.java:207)
        at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
        at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
        at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
        at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
        at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:95)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:902)
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:760)
        at com.squareup.okhttp.Call.getResponse(Call.java:274)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
        at com.squareup.okhttp.Call.execute(Call.java:81)
        at com.limelight.nvstream.http.NvHTTP.openHttpConnection(NvHTTP.java:260)
        at com.limelight.nvstream.http.NvHTTP.getAppList(NvHTTP.java:452)
        at com.limelight.nvstream.http.NvHTTP.getAppByName(NvHTTP.java:367)
        at com.limelight.nvstream.NvConnection.startApp(NvConnection.java:147)
        at com.limelight.nvstream.NvConnection.establishConnection(NvConnection.java:284)
        at com.limelight.nvstream.NvConnection.access$3(NvConnection.java:269)
        at com.limelight.nvstream.NvConnection$1.run(NvConnection.java:341)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.security.ssl.InputRecord.readFully(Unknown Source)
        at sun.security.ssl.InputRecord.read(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(Unknown Source)
        at sun.security.ssl.AppInputStream.read(Unknown Source)
        at okio.Okio$2.read(Okio.java:139)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
        ... 21 more
timeout
Starting Steam failed

**Comment by xila76** [comment]
maybe you could have more help if you post in the good repo for PC and not for android no?
