### ISSUE TITLE
Failed to receive ENet packet - Starting RSTP handshake failed

### ISSUE THREAD

**Issue by doblez** [moonlight-stream/moonlight-android#232]
Hi
Streaming on my local network works like a charm with no probs whatsoever, but as soon as I start using my external IP I get the ENet-error. I have the ports forwarded and am able to both pair, view the apps and start the game from the client, but it fails the RTSP handshake. 
Regular nvidia game stream (through nvidia software) works like a "charm", charm being 30fps and 720p..... So I'd really like to get it working over the internet too! Any ideas?
Log:

> C:\Users\danie\Downloads>java -jar moonlight-win64.jar
May 20, 2016 11:11:55 PM com.limelight.LimeLog info
INFO: Reading Preferences
May 20, 2016 11:11:56 PM com.limelight.LimeLog info
INFO: mDNS: Machine appeared: DANIEL-PC
May 20, 2016 11:11:56 PM com.limelight.LimeLog info
INFO: mDNS: Resolved (blocking)
May 20, 2016 11:11:56 PM com.limelight.LimeLog info
INFO: mDNS: Machine resolved (callback): DANIEL-PC
May 20, 2016 11:12:00 PM com.limelight.LimeLog info
INFO: Loaded key pair from disk
May 20, 2016 11:12:06 PM com.limelight.LimeLog info
INFO: Using full-screen display mode 1280x720 for 1280x720 stream
May 20, 2016 11:12:08 PM com.limelight.LimeLog info
INFO: Starting LEGO┬« Avengers
May 20, 2016 11:12:08 PM com.limelight.LimeLog info
INFO: Loaded key pair from disk
May 20, 2016 11:12:08 PM com.limelight.LimeLog info
INFO: Server major version: 7
May 20, 2016 11:12:08 PM com.limelight.LimeLog info
INFO: Using deprecated app lookup method - Please specify an app ID in your StreamConfiguration instead
May 20, 2016 11:12:11 PM com.limelight.LimeLog info
INFO: Launched new game session
May 20, 2016 11:12:11 PM com.limelight.LimeLog info
INFO: Starting RTSP handshake
java.io.IOException: Failed to receive ENet packet
        at com.limelight.nvstream.enet.EnetConnection.readPacket(EnetConnection.java:73)
        at com.limelight.nvstream.rtsp.RtspConnection.transactRtspMessageEnet(RtspConnection.java:109)
        at com.limelight.nvstream.rtsp.RtspConnection.transactRtspMessage(RtspConnection.java:143)
        at com.limelight.nvstream.rtsp.RtspConnection.requestOptions(RtspConnection.java:152)
        at com.limelight.nvstream.rtsp.RtspConnection.doRtspHandshake(RtspConnection.java:229)
        at com.limelight.nvstream.NvConnection.doRtspHandshake(NvConnection.java:264)
        at com.limelight.nvstream.NvConnection.establishConnection(NvConnection.java:320)
        at com.limelight.nvstream.NvConnection.access$3(NvConnection.java:301)
        at com.limelight.nvstream.NvConnection$1.run(NvConnection.java:373)
        at java.lang.Thread.run(Unknown Source)

In advance thanks!

**Comment by Badhoagie91** [comment]
Im having the exact same issue, I hope this issue is resolved soon. im kinda relieved that im not the only one having this issue, maybe now it will get fixed

**Comment by doblez** [comment]
Sorry for posting this the wrong place, as this problem doesn't persist on the android version, but is a windows only bug
